version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: weekly
    timezone: America/Chicago
  open-pull-requests-limit: 10
  target-branch: develop
  assignees:
  - zteater
